name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

        - run: |
            sudo apt-get update
            sudo apt-get install qemu-system
            podman machine init
            podman machine set --rootful
    
        - uses: actions/checkout@v5

        - run: podman build -t bootc .

        - run: |
            mkdir -p output
            sudo mkdir -p /var/lib/containers/storage
            podman run \
                --rm \
                -it \
                --privileged \
                --pull=newer \
                --security-opt label=type:unconfined_t \
                -v ./config.toml:/config.toml:ro \
                -v ./output:/output \
                -v /var/lib/containers/storage:/var/lib/containers/storage \
                quay.io/centos-bootc/bootc-image-builder:latest \
                --type anaconda-iso \
                --use-librepo=True \
                localhost/test-bootc:latest --rootfs xfs

        - run: ls -lah output