name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

        - run: |
            sudo apt-get update
            sudo apt-get install qemu-system
    
        - uses: actions/checkout@v5

        - name: Log in to harbor
          uses: redhat-actions/podman-login@v1
          with:
            username: ${{ secrets.HARBOR_USERNAME }}
            password: ${{ secrets.HARBOR_PASSWORD }}
            registry: ${{ secrets.HARBOR_REGISTRY }}

        - name: Extract branch name
          shell: bash
          run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          id: extract_branch
        
        - run: |
            sudo podman build \
                --build-arg USERNAME=${{ secrets.USERNAME }} \
                --build-arg PASSWORD=${{ secrets.PASSWORD }} \
                -t ${{ secrets.HARBOR_REGISTRY }}/bootc/workstation:${{ steps.extract_branch.outputs.branch }} .
        - name: Push to Harbor
          run: |
            sudo podman push ${{ secrets.HARBOR_REGISTRY }}/bootc/workstation:${{ steps.extract_branch.outputs.branch }}

#        - run: |
#            mkdir -p output
#            sudo mkdir -p /var/lib/containers/storage
#            sudo podman run \
#                --rm \
#                -it \
#                --privileged \
#                --pull=newer \
#                --security-opt label=type:unconfined_t \
#                -v /var/lib/containers/storage:/var/lib/containers/storage \
#                -v ./output:/output \
#                quay.io/centos-bootc/bootc-image-builder:latest \
#                --type anaconda-iso \
#                --use-librepo=True \
#                localhost/bootc:latest --rootfs xfs
#
#        - name: Upload a Build Artifact
#          uses: actions/upload-artifact@v4.6.2
#          with:
#            name: "Anaconda ISO"
#            path: "output/bootiso/install.iso"