name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - run: |
            podman machine init
            podman machine set --rootful
        - uses: actions/checkout@v5